version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    target-branch: source
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /
    target-branch: source
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    target-branch: source
    schedule:
      interval: monthly
