url: https://beckerfuffle.com
baseurl: ""
title: Beckerfuffle
author:
  name: Michael Becker
  url: https://beckerfuffle.com/
tagline: Go fuffle yourself!
lang: en
social:
  name: Michael Becker
  links:
    - https://github.com/mdbecker
    - https://www.linkedin.com/in/mdbecker
defaults:
  - scope:
      path: ""
    values:
      image: /images/social/beckerfuffle.png
collections:
  talks:
    output: false
toc:
  min_level: 2
  max_level: 3
  ordered_list: false
description: "Michael Becker writes about machine learning, production AI, healthcare technology, Python, and assorted technical rabbit holes."

source: source
destination: public
disable_disk_cache: true
timezone: America/New_York
permalink: /blog/:year/:month/:day/:title/
markdown: HistoricalKramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
paginate: 10
paginate_path: /posts/:num/
excerpt_separator: "<!--more-->"
category_dir: blog/categories
subscribe_rss: /atom.xml
navigation:
  - text: About
    url: /
  - text: Blog
    url: /blog/archives/
  - text: Talks
    url: /talks/
github_user: mdbecker
linkedin_user: mdbecker
twitter_user: beckerfuffle
giscus:
  repo: mdbecker/mdbecker.github.io
  repo_id: ""
  category: Comments
  category_id: ""
